"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['timelapse/__main__.py']
DATA_FILES = [
    ('', ['timelapse/resources']),
]
OPTIONS = {
    'iconfile': 'timelapse/resources/icon.icns',
}

setup(
    name="Timelapse",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
