name: CI

on:
  release:
    types: [created]
  push:
  pull_request:
  schedule:
    # Runs every Thursday at 20:23 GMT to avoid bit rot
    - cron: "20 23 * * 4"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1

    # TODO: Switch to Python action as soon as
    # https://github.com/actions/setup-python/issues/58
    # is resolved.
    # - name: Set up Python 3.8
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: 3.8
    - name: Install dependencies
      run: |
        brew install python3
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Test with pytest
      run: poetry run pytest

    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.1.0

    - name: Build app
      run: poetry run python setup.py py2app --emulate-shell-environment

    - name: Compress app
      run: |
        cd dist
        zip -r timelapse.zip Timelapse.app
        cd ../
        mv dist/timelapse.zip ./

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: timelapse.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
